### ISSUE TITLE
juicy match game view error

### ISSUE THREAD

**Issue by hamid13248** [nativegamestudio/natty-engine#3]
in android 1080dp and 4k and HD gameview is not show in screen fit
very small

**Comment by natygames** [comment]
Hi, @hamid13248, thanks you for your reply, can you give me some more specific detail on the problem, like the device number or Android version, because the test I've done seems like no problem to me.

**Comment by hamid13248** [comment]
Hi my friend🥰🥰

> Message ID: ***@***.***>
>
My device:samsung note 10
Android version 12

**Comment by hamid13248** [comment]
[](url)
![Screenshot_20231007_102509](https://github.com/nativegamestudio/natty-engine/assets/53395150/e299cd5c-2904-404b-8381-dd49b03dfd61)
![Capture](https://github.com/nativegamestudio/natty-engine/assets/53395150/fb62df2e-62ee-4211-9320-a93310b6c4bb)


error in emulator

**Comment by natygames** [comment]
Hi, @hamid13248, after testing several devices on my emulator (Pixel 2, Pixel 5, and Pixel 6), no problem occurred. The problem seems like on the camera size, please check out if the game version (1.4) and engine version (1.5) are correct, since I've changed the camera size on the last update.
